# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Thu Jun 19 22:59:44 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(834, 508)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 720))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonWidget = QtGui.QWidget(self.centralwidget)
        self.buttonWidget.setObjectName("buttonWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.buttonWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(418, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(self.buttonWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.likeButton = QtGui.QPushButton(self.buttonWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgCine/like.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.likeButton.setIcon(icon)
        self.likeButton.setIconSize(QtCore.QSize(30, 30))
        self.likeButton.setObjectName("likeButton")
        self.horizontalLayout.addWidget(self.likeButton)
        self.unlikeButton = QtGui.QPushButton(self.buttonWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imgCine/unlike.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.unlikeButton.setIcon(icon1)
        self.unlikeButton.setIconSize(QtCore.QSize(30, 30))
        self.unlikeButton.setObjectName("unlikeButton")
        self.horizontalLayout.addWidget(self.unlikeButton)
        self.gridLayout.addWidget(self.buttonWidget, 0, 0, 1, 2)
        self.infoWidget = QtGui.QWidget(self.centralwidget)
        self.infoWidget.setMinimumSize(QtCore.QSize(250, 0))
        self.infoWidget.setObjectName("infoWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.infoWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imgLabel = QtGui.QLabel(self.infoWidget)
        self.imgLabel.setMinimumSize(QtCore.QSize(200, 200))
        self.imgLabel.setText("")
        self.imgLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.imgLabel.setObjectName("imgLabel")
        self.verticalLayout.addWidget(self.imgLabel)
        self.titleLabel = QtGui.QLabel(self.infoWidget)
        self.titleLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.titleLabel.setText("")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setWordWrap(True)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.groupBox_2 = QtGui.QGroupBox(self.infoWidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(4, -1, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.starringLabel = QtGui.QLabel(self.groupBox_2)
        self.starringLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.starringLabel.setText("")
        self.starringLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.starringLabel.setWordWrap(True)
        self.starringLabel.setObjectName("starringLabel")
        self.verticalLayout_4.addWidget(self.starringLabel)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridLayout.addWidget(self.infoWidget, 1, 1, 1, 1)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableView = QtGui.QTableView(self.widget)
        self.tableView.setMaximumSize(QtCore.QSize(999999, 999999))
        self.tableView.setProperty("showDropIndicator", False)
        self.tableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableView.setCornerButtonEnabled(False)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setVisible(True)
        self.tableView.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableView)
        self.widget_2 = QtGui.QWidget(self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtGui.QGroupBox(self.widget_2)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 9, 9, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.infoLabel = QtGui.QLabel(self.groupBox)
        self.infoLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.infoLabel.setText("")
        self.infoLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.infoLabel.setWordWrap(True)
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout_3.addWidget(self.infoLabel)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Ranking Peliculas", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Ranking:", None, QtGui.QApplication.UnicodeUTF8))
        self.likeButton.setText(QtGui.QApplication.translate("MainWindow", "Subir", None, QtGui.QApplication.UnicodeUTF8))
        self.unlikeButton.setText(QtGui.QApplication.translate("MainWindow", "Bajar", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Starring:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Plot:", None, QtGui.QApplication.UnicodeUTF8))

